# Site settings
title: About Geyslan Gregório
tag_text: Geyslan Gregório
description: Here you will know more about Geyslan

# Build settings
markdown: kramdown

gems:
  - jemoji

exclude: ["README.md"]
